### ISSUE TITLE
Unable to run the test on ros kinetic

### ISSUE THREAD

**Issue by mhariharasudan** [ros-industrial/ros_canopen#210]
This is more of a question. I am trying to run the test launch file (hw_rig1.launch under canopen_test_utils) in ros-kinetic and I seem to get te following error after some timeout.
"Controller Spawner couldn't find the expected controller_manager ROS interface."

The controller manager does not seem to be running.
Debugging into the code I saw that the ControllerManagerLayer::HandleInit method in control_node.cpp is not being called. Do I have to launch something else in order to trigger the controller manager?

I am using the ros_indigo_release_candidate branch.

**Comment by mathias-luedtke** [comment]
Have you called the /rig1/driver/init service?
`canopen_test_utils` is bunch of tools we at IPA use internally and is not really maintained for external use, it was moved into a separate repository (https://github.com/ipa320/canopen_test_utils)

Please do not use `indigo_release_candidate`, it is heavily outdated, and will be removed soon.
(it is still around because it was listed in rosdistro until recently)
`indigo-devel` has the most recent code, `indigo` contains the binary-released code.

**Comment by mathias-luedtke** [comment]
For ROS kinetic please use `jade-devel` or `jade`.

**Comment by mhariharasudan** [comment]
I would like to use this package with my Elmo motors over CAN. Are there any dummy test scripts to understand the program and instructions on configuring it with a new hardware that you can point me towards?

**Comment by mathias-luedtke** [comment]
Generic hints: http://answers.ros.org/question/250174/how-to-control-maxon-motor-by-using-ros_canopen/#250180

For ROS kinetic you can use the released version of ros_canopen.
https://github.com/ipa320/canopen_test_utils contains config and launch file for **our** Elmo Controllers, some settings might be hard-coded.

On Care-O-bot we use https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/drivers/canopen_402.launch
with config like this https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_hardware_config/cob4-2/config/torso_driver.yaml

Please note that Github issues are not meant for user support like this, so I will close this issue.
If you have further questions please consider using http://answers.ros.org/ with proper tags.
