### ISSUE TITLE
sudo usage in initialize_vcan.sh

### ISSUE THREAD

**Issue by andersfischernielsen** [ros-industrial/ros_canopen#313]
`ros_canopen/socketcan_bridge/test/initialize_vcan.sh` fails to run on a ROS container in docker. 
`sudo` is unavailable in the docker container (the default user is already super user).

**Comment by mathias-luedtke** [comment]
These files in `test` are not part of any public interface, they are just for internal use.

You can make it work in Docker, if you would install `sudo` inside the container.
In addtion, this would require special precautions anway, because the container needs to use the host network and elevate some privileges (it modifies the host kernel!).
In general you should try to run container with the lowest privileges possible.
One simple work-around would be to run the script outside of Docker before starting the container.

**Comment by andersfischernielsen** [comment]
Thanks!
