### ISSUE TITLE
ROS2 development

### ISSUE THREAD

**Issue by Rayman** [ros-industrial/ros_canopen#415]
Hey,

I have a quick question about ROS2 development. I found the following repository, but the last activity is from two years ago, what is it for? It has a working ROS2 `socketcan_interface` which I need for a project.
https://github.com/ros-industrial/socketcan_interface

If that's not the right spot, is there any other ROS2 development ongoing that I'm not aware of?

**Comment by mathias-luedtke** [comment]
https://github.com/ros-industrial/socketcan_interface is marked with "DO NOT USE YET", but I have to admit that this is barely visible due to the Github layout change. It contains the initial prototype of @JWhitleyWork
It is meant to host the socketcan-related packages, once they are finsished.

The currently supported (& released) version for ROS2 is https://github.com/ros-industrial/ros_canopen/tree/dashing-devel, but it contains `can_msgs` only.

`socketcan_interface` support is a pending PR (https://github.com/ros-industrial/ros_canopen/pull/364).

In general, the ROS2 migration is tracked in https://github.com/ros-industrial/ros_canopen/issues/322, but I do not have time to work on it actively. 

---
I will close this issue in favor of #322.
