### ISSUE TITLE
refactor 402 package

### ISSUE THREAD

**Issue by floweisshardt** [ros-industrial/ros_canopen#68]
Prio A:
- timeout for homing --> done
- reflect motor state machine (switch mode, set velocities, ...)  --> done
- proper checks for mode switching 
- base class for modes (for mode layer)

Prio B:
- add 402 diagnostics (see #43)
- improve 402 threading
- move enums into namespace (402 namespace) or into SM classes
- encapsulate in base class (for motor layer)

**Comment by thiagodefreitas** [comment]
@ipa-mdl , @ipa-fmw I have started with the refactor.

For that, I have started refactoring the state machines, what I consider the kernel of the 402 and therefore the most important part to work properly.

I took the decision to change the SMs to use the boost Meta State Machine (MSM), where I can get a better view of the actions and the guards and to use the transition table, where I and anyone else in the future could have a better view of what is really happening. And also have more reliability concerning the state transitions, the mode switching and all the internals. Please, see, for a general idea:

https://github.com/thiagodefreitas/ros_canopen/blob/refactor_sm/canopen_402/include/canopen_402/state_machine.h#L165-L193

I am implementing the 402 SM and the sub-machines, as well as I want to implement a higher level SM (ON, OFF, etc...). It is not everything online,yet.

This should take quite some more time and effort, and in my opinion is a relevant change. If you have something against the approach, please inform me as soon as possible, so that I may concentrate the efforts on the other aspects.

Thanks.

**Comment by mathias-luedtke** [comment]
This sounds great, the 402 proflie is rather complicated and a clean state machine implementation would improve the robustness and maintenance.
I am a little bit concerned about the effort, but the benefits may be worth it.

**Comment by floweisshardt** [comment]
this is a critical issue for https://github.com/ipa320/ros_canopen/milestones/ROS-I%20release

@thiagodefreitas when do you think this will be finished as it is blocking us with the ROS-I release? Where can I find the modifications you already did? what is still missing?
